### ISSUE TITLE
Impossible to load the Container Polly in an arm architecture?

### ISSUE THREAD

**Issue by irigo2288** [averysmalldog/tesla-gen3wc-monitor#11]
Hello, 

The docker did not start and report this error:
standard_init_linux.go:219: exec user process caused: exec format error

I read in forum that is possibly link to ARM architecture.

Is it also possible to change the authentification data of the DB in Polly?

**Comment by averysmalldog** [comment]
Hey @irigo2288, it's definitely possible that influx/grafana have some incompatibility with ARM, I haven't looked into it yet.

As for auth data, for now it is hard coded but I do have plans in the future to read env vars so you can manage secrets on the host. You're welcome to toss in a PR if you want it sooner, for now I'm just chipping away at this every once in a while.

Edit: keeping this issue open until it gets fixed one way or another.

**Comment by irigo2288** [comment]
Grafana is OK and influx as well, only Polly do not start and gave me this error.

**Comment by averysmalldog** [comment]
Ah! I'm pretty sure I only built a Darwin x86 image and uploaded it to docker hub, that's probably what's going on. You should be able to build the image for any architecture you like - `polly` is written in Go and can be compiled however you like.
